plugin: aws_ec2
 

regions:
  - ap-southeast-1
  - us-west-1
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags['Environment']
    prefix: ""
    parent_group: "pablo" 

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
