plugin: aws_ec2

#aws_access_key: AKIA2JQTRGAEKPKCNQWL
#aws_secret_key: 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 

regions:
  - ap-southeast-1
  - us-west-1
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags['Role']
    prefix: whatever
    parent_group: "project" 

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
